var mydictionary= {};

mydictionary['Structures'] = [CBI18n.gettext("atomic"), CBI18n.gettext("collection"), CBI18n.gettext("linear"), CBI18n.gettext("hierarchical"), CBI18n.gettext("networked")];
mydictionary['Agregations'] = [CBI18n.gettext("resources and integrated resources"), CBI18n.gettext("learning objects"),CBI18n.gettext("teaching sequences"), CBI18n.gettext("training programmes, courses and plans")];
mydictionary['Status'] = [CBI18n.gettext("draft"), CBI18n.gettext("final"), CBI18n.gettext("revised"), CBI18n.gettext("unavailable")];
mydictionary['Roles'] = [CBI18n.gettext("author"), CBI18n.gettext("publisher"), CBI18n.gettext("initiator"), CBI18n.gettext("terminator"), CBI18n.gettext("validator"), CBI18n.gettext("editor"), CBI18n.gettext("graphical designer"), CBI18n.gettext("technical implementer"), CBI18n.gettext("content provider"), 
CBI18n.gettext("technical validator"), CBI18n.gettext("educational validator"), CBI18n.gettext("script writer"), CBI18n.gettext("instructional designer"), CBI18n.gettext("subject matter expert")];
mydictionary['RolesMetadata'] = [CBI18n.gettext('creator'), CBI18n.gettext('validator')];
mydictionary['TechnicalType'] = [CBI18n.gettext("operating system"), CBI18n.gettext("browser")];
mydictionary['NamesOS'] = [CBI18n.gettext("pc-dos"), CBI18n.gettext("ms-windows"), CBI18n.gettext("linux"), CBI18n.gettext("macos"), CBI18n.gettext("unix"), CBI18n.gettext("multi-os"), CBI18n.gettext("none")];
mydictionary['Browser'] = [CBI18n.gettext("any"), CBI18n.gettext("mozilla firefox"), CBI18n.gettext("netscape communicator"), CBI18n.gettext("ms-internet explorer"),CBI18n.gettext("opera"), CBI18n.gettext("amaya")];
mydictionary['InterType'] = [CBI18n.gettext("active"), CBI18n.gettext("expositive"), CBI18n.gettext("mixed")];
mydictionary['ResourceType'] = [CBI18n.gettext("photograph"), CBI18n.gettext("illustration"), CBI18n.gettext("video"), CBI18n.gettext("animation"), CBI18n.gettext("music"), CBI18n.gettext("sound effect"), CBI18n.gettext("voice-over"), CBI18n.gettext("compound audio"), CBI18n.gettext("narrative text"), CBI18n.gettext("hypertext"),
  CBI18n.gettext("computer graphics"), CBI18n.gettext("integrated media"), CBI18n.gettext("database"), CBI18n.gettext("table"), CBI18n.gettext("graph"), CBI18n.gettext("conceptual map"), CBI18n.gettext("navigation map"), CBI18n.gettext("multimedia presentation"), CBI18n.gettext("tutorial"), CBI18n.gettext("digital dictionary"), CBI18n.gettext("digital encyclopaedia"), 
  CBI18n.gettext("digital periodical publication"), CBI18n.gettext("thematic or corporate webs/web portals"), CBI18n.gettext("wiki"), CBI18n.gettext("weblog"), CBI18n.gettext("multimedia creation/edition tool"), CBI18n.gettext("web design tool"), CBI18n.gettext("office tool"), CBI18n.gettext("programming tool"), 
  CBI18n.gettext("information/knowledge analysys/organization"), CBI18n.gettext("process procedure supporting tools"), CBI18n.gettext("individual/cooperative/collaborative learning/working management tool"),
  CBI18n.gettext("multimedia creation/edition service"), CBI18n.gettext("web design service"), CBI18n.gettext("office service"), CBI18n.gettext("programming service"), CBI18n.gettext("information/knowledge analysis/organization service"), CBI18n.gettext("process/procedure supporting service"),
  CBI18n.gettext("individual/cooperative/collaborative learning/working management service","guided reading"), CBI18n.gettext("master class"), CBI18n.gettext("textual-image analysis"), CBI18n.gettext("discussion activity"), CBI18n.gettext("closed exercise or problem"),
  CBI18n.gettext("contextualized case problem"), CBI18n.gettext("open problem"), CBI18n.gettext("real or virtual learning environment"), CBI18n.gettext("didactic game"), CBI18n.gettext("webquest","experiment"), CBI18n.gettext("real project"), CBI18n.gettext("simulation"), CBI18n.gettext("questionnaire"), CBI18n.gettext("exam"), CBI18n.gettext("self assessment")];
mydictionary['InteractivityLevel'] = [CBI18n.gettext("very low"), CBI18n.gettext("low"), CBI18n.gettext("medium"), CBI18n.gettext("high"), CBI18n.gettext("very high")];
mydictionary['SemanticDensity'] = [CBI18n.gettext("very low"), CBI18n.gettext("low"), CBI18n.gettext("medium"), CBI18n.gettext("high"), CBI18n.gettext("very high")];
mydictionary['EndUser'] = [CBI18n.gettext("learner"), CBI18n.gettext("special needs learner"), CBI18n.gettext("gifted learner"), CBI18n.gettext("learners late integration into the education system"), CBI18n.gettext("learner with other specific educational support needs"), 
  CBI18n.gettext("general public"), CBI18n.gettext("individual"), CBI18n.gettext("group"), CBI18n.gettext("teacher"), CBI18n.gettext("tutor"), CBI18n.gettext("family"), CBI18n.gettext("information scientist"), CBI18n.gettext("computer scientist"), CBI18n.gettext("manager"), CBI18n.gettext("education expert"), CBI18n.gettext("subject matter expert")];
mydictionary['Context'] = [CBI18n.gettext("classroom"), CBI18n.gettext("laboratory"), CBI18n.gettext("real environment"), CBI18n.gettext("home"), CBI18n.gettext("mixed"), CBI18n.gettext("teacher"), CBI18n.gettext("tutor"), CBI18n.gettext("family"), CBI18n.gettext("schoolmate"), CBI18n.gettext("independent"), CBI18n.gettext("blended"), CBI18n.gettext("presencial"), CBI18n.gettext("face to face"), CBI18n.gettext("distance")];
mydictionary['Difficulty'] = [CBI18n.gettext("very easy"), CBI18n.gettext("easy"), CBI18n.gettext("medium"), CBI18n.gettext("difficult"), CBI18n.gettext("very difficult")];
mydictionary['CognitiveProcess'] = [CBI18n.gettext("analyse"), CBI18n.gettext("implement"), CBI18n.gettext("collaborate"), CBI18n.gettext("compare"), CBI18n.gettext("share"), CBI18n.gettext("compete"), CBI18n.gettext("understand"), CBI18n.gettext("prove"), CBI18n.gettext("communicate"), CBI18n.gettext("contextualize"), CBI18n.gettext("control"), CBI18n.gettext("cooperate"), CBI18n.gettext("create"),
  CBI18n.gettext("decide"), CBI18n.gettext("define"), CBI18n.gettext("describe"), CBI18n.gettext("discuss"), CBI18n.gettext("desing"), CBI18n.gettext("self assessment"), CBI18n.gettext("explain"), CBI18n.gettext("extrapolate"), CBI18n.gettext("innovate"), CBI18n.gettext("investigate"), CBI18n.gettext("judge"), CBI18n.gettext("motivate"), CBI18n.gettext("observe"),
  CBI18n.gettext("organize"), CBI18n.gettext("organize oneself"), CBI18n.gettext("plan"), CBI18n.gettext("practise"), CBI18n.gettext("produce"), CBI18n.gettext("recognize"), CBI18n.gettext("remember"), CBI18n.gettext("write up"), CBI18n.gettext("consider"), CBI18n.gettext("connect"), CBI18n.gettext("represent"), CBI18n.gettext("solve"), CBI18n.gettext("simulate"), CBI18n.gettext("summarize"), CBI18n.gettext("value")];
mydictionary['Cost'] = [CBI18n.gettext("yes"), CBI18n.gettext("no")];
mydictionary['AuthorRights'] = [CBI18n.gettext("propietary license"), CBI18n.gettext("free software license EUPL"), CBI18n.gettext("free software license GPL"), CBI18n.gettext("dual free content license GPL and EUPL"),
  CBI18n.gettext("other free software licenses"), CBI18n.gettext("public domain"), CBI18n.gettext("intellectual property license"), CBI18n.gettext("not appropriate"), CBI18n.gettext("creative commons: attribution"), 
  CBI18n.gettext("creative commons: attribution - non derived work"), CBI18n.gettext("creative commons: attribution - non derived work - non commercial"), CBI18n.gettext("creative commons: attribution - non commercial"),
  CBI18n.gettext("creative commons: attribution - non commercial - share alike"), CBI18n.gettext("creative commons: attribution - share alike"), CBI18n.gettext("license GFDL")];
mydictionary['Accesstype'] = [CBI18n.gettext("universal"), CBI18n.gettext("non-universal")];
mydictionary['RelationType'] = [CBI18n.gettext("ispartof"), CBI18n.gettext("haspart"), CBI18n.gettext("isversionof"), CBI18n.gettext("hasversion"), CBI18n.gettext("isformatof"), CBI18n.gettext("hasformat"), CBI18n.gettext("references"), CBI18n.gettext("isreferencedby"), CBI18n.gettext("isbasedon"), CBI18n.gettext("isbasisfor"), CBI18n.gettext("requires"), CBI18n.gettext("isrequiredby")];
mydictionary['Purposes'] = [CBI18n.gettext("discipline"), CBI18n.gettext("idea"), CBI18n.gettext("prerrequisite"), CBI18n.gettext("educational objective"), CBI18n.gettext("accesibility restrictions"), CBI18n.gettext("educational level"), CBI18n.gettext("skill level"), CBI18n.gettext("security level"), CBI18n.gettext("competency")];
module.exports = mydictionary;