/*
 * jsGeork JavaScript Library v0.0.6
 * http://jsgeork.geork.com/
 *
 * Copyright (c) 2014, www.geork.com, Jordi Cavallé | jsgeork.geork.com/licencia.txt |
 * Todos los derechos reservados.
 * 
 * Fecha: 19 Abril 2014
 */
(function(b,R,U){var Ka,X,La,P,V,Ma,ha,Na,Oa,Pa,sa,Qa,Ra,Sa,ta,I,ia,ja,Ta,Y,Z,Ua,Va,$,aa,ba,ca,Wa,Xa,Ya,ua,ka,da,ea,Za,$a,ab,bb,cb,db,D,va,wa,eb,fb,gb,hb,ib,la,jb,kb,lb,mb,nb,ob,xa,pb,qb,rb,sb,tb,ub,ya,za,Aa,Ba,ma,na,Ca,vb,Da,Ea,Fa,Ga;function Q(){}var oa="jsGeork",G=!1,pa={es:{weighting:"Ponderaci\u00f3n",total:"Total",question:"Pregunta",success:"Acierto",points:"Puntos",notanswered:"No contestado",result:"Nota",dates:"Fecha",option:"Opci\u00f3n",newtest:"Repetir",refresh:"Actualizar",delstorage:"Borrar todo",
prevres:"Resultados previos",average:"Media",check:"Comprueba",hint:"Indicio",attempts:"intentos",corrects:"correctos",previous:"Anterior",next:"Siguiente",onlynumbers:"Solo n\u00fameros",infbienvenida:"Bienvenido a la biblioteca ",infversion:"La versi\u00f3n de la biblioteca es ",infobjgbl:"La biblioteca se llama utilizando el objeto global ",infjq:"Antes de su utilizaci\u00f3n debe cargarse la biblioteca jQuery.",infme:"M\u00f3dulo con informaci\u00f3n sobre la biblioteca.",fillthegapinp:"Rellene el hueco introduciendo la soluci\u00f3n",
fillthegapsel:"Rellene el hueco seleccionando la respuesta",inpnumfill:"Introduzca un n\u00famero en el cuadro de entrada",inptxtfill:"Introduzca un texto en el cuadro de entrada",inpfill:"Introduzca un valor en el cuadro de entrada",gapko:"&#160;&#160;?&#160;&#160;",titlecheck:"Pulse para comprobar las respuestas",titlehint:"Pulse para obtener una ayuda",titlenext:"Pulse para pasar a la siguiente actividad",titleprev:"Pulse para pasar a la actividad anterior",titlenewtest:"Pulse para realizar de nuevo el test",
titlerefresh:"Pulse para actualizar la tabla",titledelsto:"Pulse para borrar el almacenamiento",fscore:"Nota obtenida $score$ sobre un total de $total$",actscore:"$score$ puntos obtenidos en la actividad $act$, $%$ de los $ptot$ puntos en juego, sobre los $total$ puntos que vale la prueba",actdone:" actividades realizadas.",actnosubmit:"Actividad por realizar.",lasttime:"Hora de la \u00faltima actualizaci\u00f3n",ok:"Correcto",ko:"Error"},ct:{weighting:"Ponderaci\u00f3",total:"Total",question:"Pregunta",
success:"Encert",points:"Punts",notanswered:"No contestat",result:"Nota",dates:"Data",option:"Opci\u00f3",newtest:"Repetir",refresh:"Actualitzar",delstorage:"Borrar tot",prevres:"Resultats previs",average:"Mitja",check:"Comprova",hint:"Indici",attempts:"intents",corrects:"correctes",previous:"Anterior",next:"Sig\u00fcent",onlynumbers:"Nom\u00e9s n\u00fameros",infbienvenida:"Benvingut a la biblioteca ",infversion:"La versi\u00f3 de la biblioteca \u00e9s ",infobjgbl:"La biblioteca es crida utilitzant l'objecte global ",
infjq:"Abans de la seva utilitzaci\u00f3 s'ha de carregar la biblioteca jQuery.",infme:"M\u00f2dul amb informaci\u00f3 sobre la biblioteca.",fillthegapinp:"Ompli el forat introduint la soluci\u00f3",fillthegapsel:"Ompli el forat seleccionant la resposta",inpnumfill:"Introdu\u00efu un n\u00famero en el quadre d'entrada",inptxtfill:"Introdu\u00efu un text en el quadre d'entrada",inpfill:"Introdu\u00efu un valor en el quadre d'entrada",gapko:"&#160;&#160;?&#160;&#160;",titlecheck:"Premi per comprovar les respostes",
titlehint:"Feu clic per obtenir una ajuda",titlenext:"Feu clic per passar a la seg\u00fcent activitat",titleprev:"Feu clic per passar a l'activitat anterior",titlenewtest:"Premi per realitzar de nou el test",titlerefresh:"Premi per actualitzar la taula",titledelsto:"Premi per esborrar l'emmagatzematge",fscore:"Nota obtinguda $score$ sobre un total de $total$",actscore:"$score$ punts obtinguts en l'activitat $act$, $%$ dels $ptot$ punts en joc, sobre $total$ punts que val la prova",actdone:" activitats realitzades.",
actnosubmit:"Activitat per realitzar.",lasttime:"Hora de l'\u00faltima actualitzaci\u00f3",ok:"Correcte",ko:"Error"}},h=pa.es||{};Ka="CSSActivity";X="CSSActFieldset";La="CSSActivityHint";P="CSSActivitySolOk";V="CSSActivitySolKo";Ma="CSSActivityOk";ha="CSSActivityButton";Na="CSSStoreButton";Oa="CSSTblTestButton";Pa="CSSTblRefreshButton";sa="CSSActivityOptPtsI";Qa="CSSActivityOptPtsS";Ra="CSSActivityOptPtsB";Sa="CSSActivityOptPtsN";ta="CSSActivityOptPtsE";I="glyphs";ia="CSSDivOut";ja="CSSInfoTextPip";
Ta="CSSInfoTextPtt";Y="CSSActivityOptOk";Z="CSSActivityOptKo";Ua="CSSActInputText";Va="CSSActInputNumber";$="CSSActInputTextKo";aa="CSSActInputTextOk";ba="CSSActInputNumberKo";ca="CSSActInputNumberOk";Wa="CSSActInputHint";Xa="CSSActInputBtnHint";Ya="CSSActInputInfo";ua="CSSActGapInput";ka="CSSActGapFillShowWords";da="CSSActGapFillOk";ea="CSSActGapFillKo";Za="CSSActGapFillOkEnd";$a="CSSActGapFillKoEnd";ab="CSSActGapFillOut";bb="CSSActGapFillOutEndOk";cb="CSSActGapFillOutEndKo";db="CSSActGapFillBtnHint";
D="CSSActGapFillFromStorage";va="CSSActivityStorageDiv";wa="CSSActivityStorageTbl";eb="CSSActivityStorageTrPair";fb="CSSActivityStorageTrOdd";gb="CSSActivityStorageTrTot";hb="CSSActivityStorageTrTotA";ib="CSSActivityStorageTrTotB";la="CSSActivityOptFilledFromStorage";jb="CSSTestForm";kb="CSSSlideControls";lb="CSSSlideCtrlPrev";mb="CSSSlideCtrlInfo";nb="CSSSlideCtrlNext";ob="CSSTrainControls";xa="CSSTrainCtrlNext";pb="CSSTrainCtrlLast";qb="CSSTestBoxSubmit";rb="CSSTestBtnSubmit";sb="CSSTrainSlider";
tb="CSSTrainSliderProgress";ub="CSSTrainSliderText";ya="CSSTestTableRes";za="CSSTestTableResTh";Aa="CSSTestTableResTrPair";Ba="CSSTestTableResTrOdd";ma="CSSTestTableResSL";na="CSSTestTableResLL";Ca="CSSTestTableResTrTot";vb="CSSTestTableResTdNew";Da="CSSTestTableResTdRefresh";Ea="CSSTestTableResTdTotA";Fa="CSSTestTableResTdTotB";Ga="CSSTestTableResTrNumAct";var fa=new Q;Q.prototype.jsGeork=function(){return oa+" 0.0.6"};var Ja=function(){function Q(c){h=b.extend({},c&&pa[c]?pa[c]:pa.es)}function M(b){this.name=
b.name||"Error";this.message=b.message;this.toString=function(){return oa+"\n\n"+this.name+": "+this.message};this.show=function(){alert(this.toString())}}function Ha(b,h){var q=!1,r="id error";b?R.getElementById(b)||(r="error, id '"+b+"' not found in document",q=!0):(r="error, nul or invalid id",q=!0);if(q)throw new M({name:h,message:r});return q}function ga(){var b=new Date;b.toJSON&&(b=b.toJSON());return b}function fa(b){var h="",q="",q=new Date(b);if(q instanceof Date){var h=q.getHours(),r=q.getMinutes(),
J=q.getSeconds(),h=h+"h:"+(10>r?"0"+r:r)+"m:"+(10>J?"0"+J:J)+"s",r=q.getMonth()+1,J=q.getDate();if(isNaN(r)||isNaN(J))return b;q=J+"/"+(10>r?"0"+r:r)+"/"+q.getFullYear();return q+"  "+h}return b}function Ia(c,h,q,r){b(r+'[data-storage-tblbox="'+q+'"] button').off("click",function(){wb(c,h,q)});b(r+'[data-storage-tblbox="'+q+'"] th').off("click keydown",function(c){9!==c.keyCode&&(b(r+'[data-storage-tblbox="'+q+'"] table').hide().attr("aria-hidden",!0),b(r+'[data-storage-tblbox="'+q+'"] div').show().attr("aria-hidden",
!1))});b(r+'[data-storage-tblbox="'+q+'"] div').off("click keydown",function(c){9!==c.keyCode&&(b(r+'[data-storage-tblbox="'+q+'"] table').show().attr("aria-hidden",!1),b(r+'[data-storage-tblbox="'+q+'"] div').hide().attr("aria-hidden",!0))});b(r+'[data-storage-tblbox="'+q+'"] button').on("click",function(){wb(c,h,q)});b(r+'[data-storage-tblbox="'+q+'"] th').on("click keydown",function(c){9!==c.keyCode&&(b(r+'[data-storage-tblbox="'+q+'"] table').hide().attr("aria-hidden",!0),b(r+'[data-storage-tblbox="'+
q+'"] div').show().attr("aria-hidden",!1).focus())});b(r+'[data-storage-tblbox="'+q+'"] div').on("click keydown",function(c){9!==c.keyCode&&(b(r+'[data-storage-tblbox="'+q+'"] table').show().attr("aria-hidden",!1),b(r+'[data-storage-tblbox="'+q+'"] div').hide().attr("aria-hidden",!0),b(r+'[data-storage-tblbox="'+q+'"] th').focus())})}function xb(b,h,q,r,x){try{var n=null;"local"===b&&localStorage&&(n=localStorage);"session"===b&&sessionStorage&&(n=sessionStorage);if(n){b={};var u=[];h?(b=JSON.parse(n.getItem(h))||
{},u=b[q]||[]):u=JSON.parse(n.getItem(q))||[];10<=u.length?u.shift():x&&1<u.length&&u.pop();u.push(r);h?(b[q]=u,n.setItem(h,JSON.stringify(b))):n.setItem(q,JSON.stringify(u))}}catch(z){G&&alert("storeResults(): "+z)}}function wb(c,h,q){try{var r=null;"local"===c&&localStorage&&(r=localStorage);"session"===c&&sessionStorage&&(r=sessionStorage);if(r)if(h){var x=JSON.parse(r.getItem(h))||{};delete x[q];r.setItem(h,JSON.stringify(x))}else r.removeItem(q);b('[data-storage-tblbox="'+q+'"]').remove()}catch(n){G&&
alert("deleteResults(): "+n)}}function qa(b,x,q,r,z){try{var n="",u=[],I=0,m="",a="",e=0,k=null,w="";if("object"===typeof q){if(q.id)m=q.id;else return"";q.url&&(a=q.url)}else m=q;"local"===b&&localStorage&&(k=localStorage);"session"===b&&sessionStorage&&(k=sessionStorage);if(k)if(x){var t=JSON.parse(k.getItem(x))||{};t[m]&&(u=t[m])}else u=t=JSON.parse(k.getItem(m))||[];if(!u||0==u.length)return"";w=u[0].type;"jsgeork.test"===w&&(w="");if(z&&"fillfromstorage"===z){for(e=0;e<u.length;++e)if("object"===
typeof u&&100==u[e].score)return z;return""}var H=u[0].name||h.prevres;x=H;a&&(x='<a href="'+a+'">'+x+"</a>");n+='<div data-storage-tblbox="'+m+'">\n';n+='\t<div tabindex="0" aria-haspopup="true" title="'+h.prevres+'" class="'+va+'" style="display: none;">[ '+H+" ]</div>\n";n+='\t<table title="'+h.prevres+'" class="'+wa+'">\n';n+='\t\t<caption title="'+m+'">'+x+"</caption>\n";n+="\t\t<thead>\n";n+='\t\t\t<tr><th tabindex="0">'+h.dates+"</th><th>"+(w?"%":h.result)+"</th></tr>\n";n+="\t\t</thead>\n";
n+="\t\t<tbody>\n";m=10;for(e=0;e<u.length;++e)"object"===typeof u&&(a=' class="'+eb+'"',e%2&&(a=' class="'+fb+'"'),H="",u[e].qbase&&"10"!=u[e].qbase.toString()&&(H="<sub>/"+u[e].qbase.toString()+"</sub>"),n+="\t\t\t<tr"+a+"><td>"+fa(u[e].date)+"</td><td>"+u[e].score+(w?"":H)+"</td></tr>\n",m=+u[e].qbase,I+=parseFloat(10*u[e].score/m));w||(e=0,w="",e=Math.round(I/u.length*100)/100,e=e*m/10,e=parseFloat(Math.round(100*e)/100),w=10!=m?e+"<sub>/"+m+"</sub>":e.toString(),n+='\t\t\t<tr class="'+gb+'"><td class="'+
hb+'">'+("session"===b?h.average+" (session)":h.average)+': </td><td class="'+ib+'">'+w+"</td></tr>\n");n+="\t\t</tbody>\n";r&&(n+="\t\t<tfoot>\n",n+='\t\t\t<tr><td colspan="2"><button type="button" title="'+h.titledelsto+'" aria-label="'+h.titledelsto+'" class="'+Na+'">'+h.delstorage+"</button></td></tr>\n",n+="\t\t</tfoot>\n");n+="\t</table>\n";return n+"</div>\n"}catch(M){return G&&alert("getResults(): "+M),""}}function x(c,z){function q(c,g){var d="",m="";try{var f=g||!1,v=!1,e="",q=la+(N?" "+
I:""),l=+c.weighting;b.isNumeric(l)&&0<=l&&100>=l&&(l=Math.abs(l),l=Math.round(l));b("#"+c.id).attr("data-weighting",l);var E=+c.lighting;b.isNumeric(E)&&0<=E&&100>=E&&(E=Math.abs(E),E=Math.round(E));b("#"+c.id).attr("data-lighting",E);l="";f&&f.form&&(l=' form="'+f.id+'_frm"');var s=b("#"+c.id);c.fieldset&&s.length&&(s.wrapInner('<fieldset name="'+c.id+'"'+l+' class="'+X+'"></fieldset>'),c.legend&&b('fieldset[name="'+c.id+'"]',s).prepend("<legend>"+c.legend+"</legend>"));f="";s=[];for(E=0;E<c.opt.length;E++)s.push(E);
c.random&&s.sort(function(){return 0.5-Math.random()});for(E=0;E<c.opt.length;E++){e="";c.list&&(f+="<li>\n");var yb="radio",k="",ra="";"multi"==c.type&&(yb="checkbox",k=' data-ok="false"',c.opt[s[E]].select&&!0===c.opt[s[E]].select&&(k=' data-ok="true"',B&&(k+=' checked="checked"',e=' class="'+q+'"')));if("single"==c.type){var p=+c.opt[s[E]].weight;b.isNumeric(p)&&0<=p&&100>=p&&(p=Math.abs(p),p=Math.round(p),ra=' data-weight="'+p+'"',B&&100===p&&!v&&(ra+=' checked="checked"',e=' class="'+q+'"',v=
!0))}f+='<label for="'+c.id+"_item"+s[E]+'" id="'+c.id+"_item"+s[E]+'_label"'+e+">\n";m="";a["wai-aria"]&&(0<b("#"+c.id+"_info_aria").length&&(m=' aria-describedby="'+c.id+'_info_aria"'),m+=' aria-labelledby="'+c.id+"_item"+s[E]+'_label"');f+='<input type="'+yb+'" name="'+c.id+'"'+m+' data-answer="'+c.opt[s[E]].answer+'"'+k+ra+' id="'+c.id+"_item"+s[E]+'"'+l+" />\n";f+=c.opt[s[E]].text+"</label>\n";c.list&&(f+="</li>\n")}c.list&&(f="ul"==c.list?"<ul>\n"+f+"</ul>\n":"<ol>\n"+f+"</ol>\n");var d=d+f,
n=h.check;c.button&&(n=c.button);d+='<button type="button" id="'+c.id+'_btn" title="'+h.titlecheck+'"'+(a["wai-aria"]?' aria-label="'+h.titlecheck+'"':"")+'  class="'+ha+'">'+n+"</button>";d+='<div id="'+c.id+'_out" class="'+ia+'"></div>\n';b("#"+c.id+" fieldset").length?b("#"+c.id+" fieldset").append(d):b("#"+c.id).append(d);var r=b('[data-info-bottom="'+c.id+'"]').html();if(r){var K='<div id="'+c.id+'_info_bottom" class="'+ja+'">'+r+"</div>\n";b("#"+c.id+" fieldset").length?b("#"+c.id+" fieldset").append(K):
b("#"+c.id).append(K)}}catch(t){G&&alert("makeHtmlQuestion(): "+t)}return d}function r(c,d){try{var g=d||!1,f="",m=h.inpfill;g&&g.form&&(f=' form="'+g.id+'_frm"');var v=b("#"+c.id);if(c.fieldset&&v.length){v.wrapInner('<fieldset name="'+c.id+'"'+f+' class="'+X+'"></fieldset>');var e=b('[data-info-bottom="'+c.id+'"]').html();e&&b('fieldset[name="'+c.id+'"]',v).prepend('<div id="'+c.id+'_info_bottom" class="'+ja+'">'+e+"</div>\n");c.legend&&b('fieldset[name="'+c.id+'"]',v).prepend("<legend>"+c.legend+
"</legend>")}var q=b('[data-makeqs="'+c.id+'"]');b("[data-input-make]",q).each(function(d){if(b(this).attr("data-input-make").length){d=c.boxs[b(this).attr("data-input-make")];if("undefined"==typeof d||"text"===d.type){var p="",v=b(this).text();v&&b.trim(v);var e=v.length,s="";if(d){for(var l=0;l<d.values.length;++l)0===l&&(s=d.values[l]),d.values[l].length>e&&(e=d.values[l].length);switch(d.adjustgaps){case "all":p+=' maxlength="'+e+'" size="'+e+'"';break;case "size":p+=' size="'+e+'"';break;case "maxlength":p+=
' maxlength="'+e+'"'}switch(d.autocomplete){case "on":p+=' autocomplete="on"';break;case "off":p+=' autocomplete="off"'}d.placeholder&&(p+=' placeholder="'+d.placeholder+'"');g&&g.form&&(p+=f);l=+d.weight;b.isNumeric(l)&&0<=l&&100>=l&&(l=Math.abs(l),l=Math.round(l),p+=' data-weight="'+l+'"');m=d["aria-label"]||h.inpfill}v&&(p+=' data-input-value="'+v+'"');B&&(b(this).addClass(D),p+=' value="'+(v?v:s)+'"');p='<input type="text" data-input-type="text" data-box="'+b(this).attr("data-input-make")+'" title="'+
h.inptxtfill+'"'+(a["wai-aria"]?' aria-label="'+m+'"':"")+' class="'+Ua+'"'+p+" />";b(this).html(p)}if(d&&"number"===d.type){p="";(v=b(this).text())&&b.trim(v);e=v.length;s="";if(d){for(l=0;l<d.values.length;++l)0===l&&(s=d.values[l]),d.values[l].toString().length>e&&(e=d.values[l].toString().length);switch(d.adjustgaps){case "all":p+=' maxlength="'+e+'" size="'+e+'"';break;case "size":p+=' size="'+e+'"';break;case "maxlength":p+=' maxlength="'+e+'"'}switch(d.autocomplete){case "on":p+=' autocomplete="on"';
break;case "off":p+=' autocomplete="off"'}d.placeholder&&(p+=' placeholder="'+d.placeholder+'"');g&&g.form&&(p+=f);l=+d.weight;b.isNumeric(l)&&0<=l&&100>=l&&(l=Math.abs(l),l=Math.round(l),p+=' data-weight="'+l+'"');d.decimals&&"number"===typeof d.decimals&&0<=d.decimals&&(p+=' data-input-decimals="'+d.decimals+'"');d.tofixed&&"number"===typeof d.tofixed&&0<=d.tofixed&&(p+=' data-input-tofixed="'+d.tofixed+'"');"number"===typeof d.accuracy&&50<=d.accuracy&&100>=d.accuracy&&(p+=' data-input-accuracy="'+
d.accuracy+'"');d.min&&d.max&&d.max>=d.min&&(p+=' data-input-min="'+d.min+'" data-input-max="'+d.max+'"');if(!B&&"number"===typeof d.decimals&&0<=d.decimals){e="#";if(0<d.decimals)for(e+=".",l=0;l<d.decimals;l++)e+="#";p+=' value="'+e+'"'}m=d["aria-label"]||h.inpfill}v&&(p+=' data-input-value="'+v+'"');B&&(b(this).addClass(D),p+=' value="'+(v?v:s)+'"');p='<input type="text" data-input-type="number" data-box="'+b(this).attr("data-input-make")+'" title="'+h.inpnumfill+'"'+(a["wai-aria"]?' aria-label="'+
m+'"':"")+' class="'+Va+'"'+p+" />";p+="<span style='color: red; display: none;' class='onlynum'>"+h.onlynumbers+"</span>";b(this).html(p)}}});var v="",l=b('[data-input-btnchek="'+c.id+'"]'),k=h.check;c.button&&(k=c.button);v+='<button type="button" id="'+c.id+'_btn" title="'+h.titlecheck+'"'+(a["wai-aria"]?' aria-label="'+h.titlecheck+'"':"")+' class="'+ha+'">'+k+"</button>";l.html(v);var s=b('[data-input-btnhint="'+c.id+'"]');if(c.hint&&s.length){v='<button type="button" id="'+c.id+'_btnhint" title="'+
h.titlehint+'"'+(a["wai-aria"]?' aria-label="'+h.titlehint+'"':"")+' class="'+Xa+'">';v=c.btnhint?v+c.btnhint:v+h.hint;s.html(v+"</button>\n");var n=b('[data-info-hint="'+c.id+'"]');"yes"!==n.attr("data-info-noclass")&&n.addClass(Wa)}}catch(r){G&&alert("makeHtmlInputs(): "+r)}}function J(c,d){var g="";try{var f=d||!1,e="";f&&f.form&&(e=' form="'+f.id+'_frm"');var v=+c.weighting;b.isNumeric(v)&&0<=v&&100>=v&&(v=Math.abs(v),v=Math.round(v));b("#"+c.id).attr("data-weighting",v);var m=b("#"+c.id);c.fieldset&&
m.length&&(m.wrapInner('<fieldset name="'+c.id+'"'+e+' class="'+X+'"></fieldset>'),c.legend&&b('fieldset[name="'+c.id+'"]',m).prepend("<legend>"+c.legend+"</legend>"));var g=g+('<div id="'+c.id+'_out" class="'+ia+'"></div>\n'),q=h.check;c.button&&(q=c.button);g+='<button type="button" id="'+c.id+'_btn" title="'+h.titlecheck+'"'+(a["wai-aria"]?' aria-label="'+h.titlecheck+'"':"")+' class="'+ha+'">'+q+"</button>";c.hint&&(g+='<button type="button" id="'+c.id+'_btnhint" title="'+h.titlehint+'"'+(a["wai-aria"]?
' aria-label="'+h.titlehint+'"':"")+' class="'+db+'" style="display: none;">',g=c.btnhint?g+c.btnhint:g+h.hint,g+="</button>\n");b("#"+c.id+" fieldset").length?b("#"+c.id+" fieldset").append(g):b("#"+c.id).append(g);var l=b('[data-info-bottom="'+c.id+'"]').html();if(l){var k='<div id="'+c.id+'_info_bottom" class="'+ja+'">'+l+"</div>\n";b("#"+c.id+" fieldset").length?b("#"+c.id+" fieldset").append(k):b("#"+c.id).append(k)}}catch(s){G&&alert("makeHtmlQuestionGapFill(): "+s)}return g}function n(c,d){var g=
d||!1,f="",e="",v=h.fillthegapinp;g&&g.form&&(f=' form="'+g.id+'_frm"');e="";a["wai-aria"]&&0<b("#"+c.id+"_info_aria").length&&(e=' aria-describedby="'+c.id+'_info_aria"');var m=b('[data-makeqs="'+c.id+'"]');b("[data-gap-fill]",m).each(function(d){if(b(this).attr("data-gap-fill").length){d="";var l=c.gaps[b(this).attr("data-gap-fill")],m=b(this).text();m&&b.trim(m);var s=m.length,q="";if(l){for(var k=0;k<l.words.length;++k)0===k&&(q=l.words[k]),l.words[k].length>s&&(s=l.words[k].length);switch(l.adjustgaps){case "all":d+=
' maxlength="'+s+'" size="'+s+'"';break;case "size":d+=' size="'+s+'"';break;case "maxlength":d+=' maxlength="'+s+'"'}switch(l.autocomplete){case "on":d+=' autocomplete="on"';break;case "off":d+=' autocomplete="off"'}l.placeholder&&(d+=' placeholder="'+l.placeholder+'"');g&&g.form&&(d+=f);s=+l.weight;b.isNumeric(s)&&0<=s&&100>=s&&(s=Math.abs(s),s=Math.round(s),d+=' data-weight="'+s+'"');v=l["aria-label"]||h.fillthegapinp}m&&(d+=' data-gap-word="'+m+'"');B&&(b(this).addClass(D),d+=' value="'+(m?m:
q)+'"');b(this).html('<input type="text" data-gap="'+b(this).attr("data-gap-fill")+'"'+e+' title="'+h.fillthegapinp+'"'+(a["wai-aria"]?' aria-label="'+v+'"':"")+' class="'+ua+'"'+d+" />")}});b("[data-gap-select]",m).each(function(d){if(b(this).attr("data-gap-select").length){d="";var l=c.gaps[b(this).attr("data-gap-select")],m=b(this).text();m&&b.trim(m);var s=[],k=0,q=0,n="";s.push(m);if(l){for(k=0;k<l.words.length;++k)s.push(l.words[k]);g&&g.form&&(d+=f);k=+l.weight;b.isNumeric(k)&&0<=k&&100>=k&&
(k=Math.abs(k),k=Math.round(k),d+=' data-weight="'+k+'"');v=l["aria-label"]||h.fillthegapinp}s.sort(function(){return 0.5-Math.random()});if(B)for(k=0;k<s.length;++k)s[k]===m&&(q=k);n+='<select data-gap="'+b(this).attr("data-gap-select")+'" data-gap-word="'+m+'"'+e+' title="'+h.fillthegapsel+'"'+(a["wai-aria"]?' aria-label="'+l["aria-label"]+'"':"")+' class="'+ua+'"'+d+">\n";n+="<option>&#160;</option>\n";for(k=0;k<s.length;++k)l="",B&&k===q&&(l=' selected="selected"'),n+="<option"+l+">",n+=s[k],
n+="</option>\n";n+="</select>\n";B&&(b(this).addClass(D),d+=' selected="selected"');b(this).html(n)}})}function u(){try{t++;var c=b('[data-makeqs="'+a.id+'"]');b("[data-gap-fill]",c).each(function(c){if(b("input",this).length){c=b("input",this).val();var d=b("input",this).attr("data-gap-word");if(!d){var g=a.gaps[b(this).attr("data-gap-fill")];g&&g.words.length&&(d=g.words[0])}g="?";if(d){var d=d.split(""),h=0,g="",h=Math.floor(Math.random()*(d.length-1+1-0)+0);for(C=0;C<d.length;++C)C==h?(g+=d[C],
1<t&&(h=Math.floor(Math.random()*(d.length-1+1-0)+0))):g=" "===d[C]?g+" ":g+"_"}a.hint&&"string"===typeof a.hint&&"html5"===a.hint.toLowerCase()?b("input",this).attr("placeholder",g):0===b.trim(c).length&&b("input",this).val(g)}});b(this).prop("disabled",!0)}catch(d){G&&alert("hintGapFills(): "+d)}}function S(){try{var c=e.attr("data-weighting")||100,d=e.attr("data-lighting")||0,g=0;++w;x.attempts=w;x.score=0;x.objscore={};switch(a.type){case "input":var f=0,q=0,v=0,n=0,r=b('[data-makeqs="'+a.id+
'"]'),f=b("[data-input-make]",r).length;b("[data-input-make]",r).each(function(c){if(b("input",this).length){c=a.boxs[b(this).attr("data-input-make")];if("undefined"==typeof c||"text"===c.type){q++;var d=b.trim(b("input",this).val()).toString(),g=!1,f=b("input",this).attr("data-input-value"),h=parseInt(b("input",this).attr("data-weight"),10)||100;c&&c.casesensitive?d===f&&(g=!0):d&&f&&d.toLowerCase()===f.toLowerCase()&&(g=!0);if(!g&&c&&c.values)for(var l=0;l<c.values.length;++l)c.casesensitive?d===
c.values[l]&&(g=!0):d&&c.values[l]&&d.toLowerCase()===c.values[l].toLowerCase()&&(g=!0);g?(b(this).removeClass($+" "+aa).addClass(aa),q--,v+=h/100):(b(this).removeClass($+" "+aa),b(this).addClass($));n+=h/100}if(c&&"number"===c.type){q++;var d=b.trim(b("input",this).val()),g=!1,f=b("input",this).attr("data-input-value"),e=b("input",this).attr("data-input-tofixed"),k=b("input",this).attr("data-input-min"),p=b("input",this).attr("data-input-max"),s=b("input",this).attr("data-input-accuracy"),h=parseInt(b("input",
this).attr("data-weight"),10)||100,f=parseFloat(f);if(!f||!b.isNumeric(f))for(l=0;l<c.values.length&&(f=parseFloat(c.values[l]),!b.isNumeric(f));++l);if(!b.isNumeric(f))k&&p&&b.isNumeric(k)&&b.isNumeric(p)&&p>=k&&b.isNumeric(d)?parseFloat(d)>=parseFloat(k)&&parseFloat(d)<=parseFloat(p)&&(g=!0):b("input",this).val("error");else if(d&&b.isNumeric(d))if(d=parseFloat(d),d===f)g=!0;else if(e&&b.isNumeric(e)&&(0>e&&(e=0),d.toFixed(e)===f.toFixed(e)&&(g=!0)),s&&b.isNumeric(s)&&0<=s&&100>=s&&(l=Math.abs(f)*
(1-s/100),d>=f-l&&d<=f+l&&(g=!0)),k&&p&&b.isNumeric(k)&&b.isNumeric(p)&&p>=k&&parseFloat(d)>=parseFloat(k)&&parseFloat(d)<=parseFloat(p)&&(g=!0),c&&c.values)for(l=0;l<c.values.length;++l)if(b.isNumeric(parseFloat(c.values[l]))&&d===parseFloat(c.values[l])){g=!0;break}g?(b(this).removeClass(ba+" "+ca).addClass(ca),q--,v+=h/100):b(this).removeClass(ba+" "+ca).addClass(ba);n+=h/100}m&&b("input",this).prop("disabled",!0)}});var l=Ya;if(a.attempts==w||m)H=!0;g=Math.round(v/n*100);0===q&&(y.hide(),a.hint&&
F.hide());g>=a.threshold?(b('[data-info-ok="'+a.id+'"]').show(),b('[data-info-ko="'+a.id+'"]').hide(),a["wai-aria"]&&(b('[data-info-ok="'+a.id+'"]').attr("aria-hidden",!1),b('[data-info-ko="'+a.id+'"]').attr("aria-hidden",!0))):(b('[data-info-ok="'+a.id+'"]').hide(),b('[data-info-ko="'+a.id+'"]').show(),a["wai-aria"]&&(b('[data-info-ok="'+a.id+'"]').attr("aria-hidden",!0),b('[data-info-ko="'+a.id+'"]').attr("aria-hidden",!1),b('[data-input-showinfo="'+a.id+'"]').length&&y.attr("aria-describedby",
a.id+"_inputinfo")));var K=b('[data-input-showinfo="'+a.id+'"]');if(0<K.length){var s='<div id="'+a.id+'_inputinfo" class="'+l+'"'+(a["wai-aria"]?' role="status"':"")+">";m||(s+=w+" "+h.attempts+"<br />");s+=f-q+"/"+f+" "+h.corrects;s+="</div>";K.slideToggle();K.html(s);K.slideToggle()}m&&b("#"+k+"_results").append('\t<div data-type="'+a.type+'" data-id="'+a.id+'" data-weight="'+g+'" data-weighting="'+c+'" data-lighting="'+d+'"></div>\n');break;case "gapfill":var t=0,u=0,n=v=0,L=b('[data-makeqs="'+
a.id+'"]'),t=b("[data-gap-fill]",L).length+b("[data-gap-select]",L).length;b("[data-gap-fill]",L).each(function(c){if(b("input",this).length){u++;var d=b.trim(b("input",this).val()),g=a.gaps[b(this).attr("data-gap-fill")],f=!1,l=b("input",this).attr("data-gap-word"),k=b("input",this).attr("data-gap"),p=parseInt(b("input",this).attr("data-weight"),10)||100;a.hint&&F.show();g&&g.casesensitive?d===l&&(f=!0):d&&l&&d.toLowerCase()===l.toLowerCase()&&(f=!0);if(!f&&g){for(var s="",q=!1,r=0;r<g.words.length;++r)s+=
g.words[r]+", ",g.casesensitive?d===g.words[r]&&(q=f=!0,g.showwords&&(d+="<sup>["+c+"]</sup>")):d&&g.words[r]&&d.toLowerCase()===g.words[r].toLowerCase()&&(q=f=!0,g.showwords&&(d+="<sup>["+c+"]</sup>"));q&&s.length&&g.showwords&&(s=s.substring(0,s.length-2),b("."+ka,e).length||b("#"+a.id+"_out",e).before('<div class="'+ka+'"></div>'),b("."+ka,e).append("<sup>["+c+"]</sup> "+(l?l:"?")+" = "+s+"<br />"))}d&&""!==b.trim(d)||(d=h.gapko);f?(b(this).html('<span data-gap="'+k+'" data-gap-result="ok" data-weight="'+
p+'"'+(a["wai-aria"]?' aria-label="'+h.ok+'" aria-describedby="'+a.id+'_out"':"")+' tabindex="0" class="'+da+'">'+d+"</span>"),u--,v+=p/100):(a.attempts===w||m)&&b(this).html('<span data-gap="'+k+'" data-gap-result="ko" data-weight="'+p+'"'+(a["wai-aria"]?' aria-label="'+h.ko+'" aria-describedby="'+a.id+'_out"':"")+' tabindex="0" class="'+ea+'">'+d+"</span>");n+=p/100}else b('[data-gap-result="ok"]',this).length&&(p=parseInt(b('[data-gap-result="ok"]',this).attr("data-weight"),10)||100,v+=p/100,n+=
p/100)});b("[data-gap-select]",L).each(function(c){if(b("select",this).length){u++;c=b("select",this).val();var d=!1,g=parseInt(b("select",this).attr("data-weight"),10)||100,f=b("input",this).attr("data-gap");b("select",this).attr("data-gap-word")===c&&(d=!0);c&&""!==b.trim(c)||(c=h.gapko);d?(b(this).html('<span data-gap="'+f+'" data-gap-result="ok" data-weight="'+g+'"'+(a["wai-aria"]?' aria-label="'+h.ok+'" aria-describedby="'+a.id+'_out"':"")+' tabindex="0" class="'+da+'">'+c+"</span>"),u--,v+=
g/100):(a.attempts==w||m)&&b(this).html('<span data-gap="'+f+'" data-gap-result="ko" data-weight="'+g+'"'+(a["wai-aria"]?' aria-label="'+h.ko+'" aria-describedby="'+a.id+'_out"':"")+' tabindex="0" class="'+ea+'">'+c+"</span>");n+=g/100}else b('[data-gap-result="ok"]',this).length&&(g=parseInt(b('[data-gap-result="ok"]',this).attr("data-weight"),10)||100,v+=g/100,n+=g/100)});var g=Math.round(v/n*100),l=ab,f="",p;g>=a.threshold?(p=b('[data-info-ok="'+a.id+'"]'),p.length&&(f='\n<div class="'+P+'">'+
p.html()+"</div>")):(p=b('[data-info-ko="'+a.id+'"]'),p.length&&(f='\n<div class="'+V+'">'+p.html()+"</div>"));if(a.attempts==w||0===u||m)H=!0,l=0===u?l+(" "+bb):l+(" "+cb),b("."+da,L).removeClass(da).addClass(Za),b("."+ea,L).removeClass(ea).addClass($a),a.hint&&F.hide(),b("#"+a.id+"_btn",e).hide(),a["wai-aria"]&&b("#"+a.id+"_btn",e).attr("aria-hidden",!0);s='<div class="'+l+'"'+(a["wai-aria"]?' role="status"':"")+">";m||(s+=w+(0<a.attempts?"/"+a.attempts:"")+" "+h.attempts+"<br />");s+=t-u+"/"+t+
" "+h.corrects;s+="</div>\n";b("#"+a.id+"_out").slideToggle();b("#"+a.id+"_out").html(s+f);b("#"+a.id+"_out").slideToggle();m&&b("#"+k+"_results").append('\t<div data-type="'+a.type+'" data-id="'+a.id+'" data-weight="'+g+'" data-weighting="'+c+'" data-lighting="'+d+'"></div>\n');break;case "multi":var z="";b("input[type=checkbox]:checked",e).each(function(){var c=b(this).attr("data-answer"),d="",g="";c&&(d=b("[data-opt="+b(this).attr("data-answer")+"]",e).html(),g=a.id+"_out_"+c);d||(d="");z+="<div"+
(g?' id="'+g+'"':"")+">\n"+d+"</div>\n";a["wai-aria"]&&b(this).attr("aria-describedby",a.id+"_result"+(g?" "+g:""))});var t=b("input[type=checkbox]",e),A=t.length,C=0;t.each(function(){this.checked?"true"==b(this).attr("data-ok")?(C++,!m&&a.optsuccess&&b(this).parent().addClass(Y+(N?" "+I:""))):!m&&a.optsuccess&&b(this).parent().addClass(Z+(N?" "+I:"")):"false"==b(this).attr("data-ok")&&C++});g=Math.round(C/A*100);l="";s=La;if(a.hint||C===A)l=C.toString()+"/"+A.toString();f="";C===A&&(s+=" "+Ma,l=
"<strong>"+l+" 100%</strong>",y.prop("disabled",!0));g>=a.threshold?(p=b('[data-info-ok="'+a.id+'"]'),p.length&&(f='\n<div class="'+P+'">'+p.html()+"</div>")):(p=b('[data-info-ko="'+a.id+'"]'),p.length&&(f='\n<div class="'+V+'">'+p.html()+"</div>"));l='<div  class="'+s+'"'+(a["wai-aria"]?' role="status"':"")+">\n"+l+"\n</div>";l='<div id="'+a.id+'_result">\n'+l+f+"\n</div>\n";R.getElementById(a.id+"_result")&&(R.getElementById(a.id+"_result").style.display="block");O.html(l+z);m?(t.prop("disabled",
!0),0<t.length&&b("#"+k+"_results").append('\t<div data-type="'+a.type+'" data-id="'+a.id+'" data-weight="'+g+'" data-weighting="'+c+'" data-lighting="'+d+'"></div>\n')):(b(this).prop("disabled",!0),t[0].focus(),g>=a.threshold||t[0].scrollIntoView());break;case "single":var B=b("input[type=radio]:checked",e);if(0<B.length){var f=z="",J=B.attr("data-answer");J&&(z=b("[data-opt="+J+"]",e).html());g=B.attr("data-weight")||0;g=parseFloat(g);g>=a.threshold?(!m&&a.optsuccess&&B.parent().addClass(Y+(N?" "+
I:"")),p=b('[data-info-ok="'+a.id+'"]'),p.length&&(f='\n<div class="'+P+'">'+p.html()+"</div>")):(!m&&a.optsuccess&&B.parent().addClass(Z+(N?" "+I:"")),p=b('[data-info-ko="'+a.id+'"]'),p.length&&(f='\n<div class="'+V+'">'+p.html()+"</div>"));O.html(f+z);a["wai-aria"]&&B.attr("aria-describedby",a.id+"_out");if(m){var S=B.attr("id");b("#"+k+"_results").append('\t<div data-type="'+a.type+'" data-id="'+a.id+'" data-selected="'+S+'" data-weight="'+g+'" data-weighting="'+c+'" data-lighting="'+d+'"></div>\n')}else g>=
a.threshold?b("#"+a.id+" ."+P).length&&b("#"+a.id+" ."+P)[0].scrollIntoView():b("#"+a.id+" ."+V).length&&b("#"+a.id+" ."+V)[0].scrollIntoView()}else m&&b("#"+k+"_results").append('\t<div data-type="'+a.type+'" data-id="'+a.id+'" data-weight="none" data-weighting="'+c+'" data-lighting="0"></div>\n');m?b("input[type=radio]",e).prop("disabled",!0):(b(this).prop("disabled",!0),B.focus())}100<=g&&(w=0);T=g>=a.threshold?!0:!1;x.objscore.type=a.type;x.objscore.id=a.id;x.objscore.name=a.name;x.objscore.weighting=
c;x.objscore.lighting=d;x.objscore.date=ga();x.objscore.score=g;x.score=g;x.update=a.id;!m&&a.storage&&xb(a.storage,a.storagekey,a.id,{type:"jsgeork."+a.type,id:a.id,name:a.name,weighting:a.weighting,lighting:a.lighting,score:x.score,qbase:"100",date:ga()},!0);try{x[a.id]=x.objscore}catch(Eb){}}catch(D){D instanceof M?D.show():G&&alert("setQuestion.checkSolution(): "+D)}}var m=z||!1,a,e,k,w=0,t=0,H=!1,T=!1,N=!0;try{if("object"!==typeof c)throw new M({name:"Data error",message:"bad object"});if("input"==
c.type||!Ha(c.id,c.name||c.legend))if(U.jQuery){c.lang&&Q(c.lang);W=c;a=b.extend({},Ab,W);for(var N="csshexent"===a.icons?!0:!1,C=0;C<a.opt.length;C++)a.opt[C]=b.extend({},Bb,W.opt[C]);for(var A in W.boxs)a.boxs[A]=b.extend({},Cb,W.boxs[A]);for(A in W.gaps)a.gaps[A]=b.extend({},Db,W.gaps[A]);x.lastcall=a.id;x.attempts=0;x.score=0;x.objscore=null;x.update=a.id;e=b("#"+a.id);m&&(k=m.id);0<e.length&&(a.clase?e.addClass(a.clase):e.addClass(Ka));var B=!1;!m&&a.fillfromstorage&&"fillfromstorage"===qa(a.storage,
a.storagekey,a.id,a.delstorage,"fillfromstorage")&&(B=!0);var y,F,O;switch(a.type){case "input":r(a,m);y=b("#"+a.id+"_btn");a.hint&&(F=b("#"+a.id+"_btnhint"));B||y.prop("disabled",!0);break;case "gapfill":J(a,m);n(a,m);y=b("#"+a.id+"_btn",e);a.hint&&(F=b("#"+a.id+"_btnhint",e));B?a.hint&&F.prop("disabled",!0):y.prop("disabled",!0);break;case "single":case "multi":q(a,m),y=b("#"+a.id+"_btn",e),a.hint&&(F=b("#"+a.id+"_btnhint",e)),O=b("#"+a.id+"_out",e)}"single"!==a.type||B||y.prop("disabled",!0);if("single"===
a.type)b("input",e).on("change",function(){O.html("");y.prop("disabled",!1);b("label",e).removeClass(la).removeClass(I).removeClass(Y).removeClass(Z);a["wai-aria"]&&b("input",e).removeAttr("aria-describedby")});if("multi"===a.type)b("input",e).on("change",function(){O.html("");R.getElementById(a.id+"_result")&&(R.getElementById(a.id+"_result").style.display="none");y.prop("disabled",!1);b("label",e).removeClass(la).removeClass(I).removeClass(Y).removeClass(Z);a["wai-aria"]&&(b("#"+a.id+"_info_aria").length?
b("input",e).attr("aria-describedby",a.id+"_info_aria"):b("input",e).removeAttr("aria-describedby"))});if("input"===a.type){var g=b('[data-makeqs="'+a.id+'"]');b("input",g).on("keyup change",function(c){9===c.keyCode||c.shiftKey||(m||(y.prop("disabled",!1),b("#"+a.id+"_inputinfo").hide(),a["wai-aria"]&&b("#"+a.id+"_inputinfo").attr("aria-hidden",!0),y.show(),b('[data-info-ok="'+a.id+'"]').hide(),b('[data-info-ko="'+a.id+'"]').hide(),a["wai-aria"]&&(b('[data-info-ok="'+a.id+'"]').attr("aria-hidden",
!0),b('[data-info-ko="'+a.id+'"]').attr("aria-hidden",!0)),a["wai-aria"]&&y.removeAttr("aria-describedby")),a.hint&&F.show())});b('[data-input-make] input[data-input-type="text"]',g).on("keyup keydown change",function(a){9===a.keyCode||a.shiftKey||(b(this).parent().removeClass(aa+" "+$),b(this).parent().removeClass(D))});b('[data-input-make] input[ data-input-type="number"]',g).on("keyup keydown change",function(a){9===a.keyCode||a.shiftKey||(b(this).parent().removeClass(ca+" "+ba),b(this).parent().removeClass(D),
b(this).val()&&b.trim(b(this).val())&&!b.isNumeric(b(this).val())?b(".onlynum",b(this).parent()).fadeIn("slow"):b(".onlynum",b(this).parent()).fadeOut("slow"))});if(a.hint)F.on("click",function(){b('[data-info-hint="'+a.id+'"]').toggle()})}if("gapfill"===a.type){var d=b('[data-makeqs="'+a.id+'"]');b("input,select",d).on("keypress keydown change",function(a){9===a.keyCode||a.shiftKey||(m||y.prop("disabled",!1),b(this).parent().removeClass(D))});if(a.hint){b("input",d).length&&F.show();F.on("click",
u);var K=b("input",d);K.on("keypress change",function(a){try{if(9!==a.keyCode&&!a.shiftKey){var c=!1;0<K.length?(F.show(),K.each(function(){""===b.trim(b(this).val())&&(c=!0)})):F.hide();c?F.prop("disabled",!1):F.prop("disabled",!0)}}catch(d){G&&alert("gap onchange(): "+d)}})}}if(m)y.hide(),b("#"+m.id+"_btn").on("click",S);else if(y.on("click",S),a.showstorage){var f=qa(a.storage,a.storagekey,a.id,a.delstorage);if(f='<div data-store-wrap="'+a.id+'">\n'+f+"</div>\n")b('[data-stored-results="'+a.id+
'"]').length?b('[data-stored-results="'+a.id+'"]').html(f):b("#"+a.id+' fieldset[name="'+a.id+'"]').length?b("#"+a.id+' fieldset[name="'+a.id+'"]').append(f):b("#"+a.id).append(f),Ia(a.storage,a.storagekey,a.id,'[data-store-wrap="'+a.id+'"] '),b('[data-storage-tblbox="'+a.id+'"] table').hide().attr("aria-hidden",!0),b('[data-storage-tblbox="'+a.id+'"] div').show().attr("aria-hidden",!1)}if("function"===typeof a.oncheck&&(A=function(){a.oncheck.call(x)},y.on("click",A),m))b("#"+m.id+"_btn").on("click",
A);if("function"===typeof a.oncomplete&&(A=function(){"gapfill"!==a.type&&"input"!==a.type||!H||a.oncomplete.call(x)},y.on("click",A),m))b("#"+m.id+"_btn").on("click",A);A=function(){if("single"===a.type||"multi"===a.type||"input"===a.type||"gapfill"===a.type)T?("function"===typeof a.onok&&a.onok.call(x),a.onchecker&&"function"===typeof a.onchecker&&a.onchecker.call(x)):"function"===typeof a.onko&&a.onko.call(x)};y.on("click",A);if(m)b("#"+m.id+"_btn").on("click",A);"function"===typeof a.onready&&
a.onready.call(x)}else R.getElementById(a.id).innerHTML="<span style='color: red;'>This requires jQuery!</span>"}catch(L){L instanceof M?L.show():G&&alert("setQuestion(): "+L)}}function z(c){function D(a){a>m.length-1||("multi"===m[a].type&&b("#"+m[a].id+" input[type=checkbox]").length&&b("#"+m[a].id+" input[type=checkbox]")[0].focus(),"single"===m[1].type&&b("#"+m[a].id+" input[type=radio]").length&&b("#"+m[a].id+" input[type=radio]")[0].focus(),"input"===m[w+1].type&&b("#"+m[a].id+" input[type=text]").length&&
b("#"+m[a].id+" input[type=text]")[0].focus(),"gapfill"===m[a].type&&b("#"+m[a].id+" input[type=text], #"+m[a].id+" select").length&&b("#"+m[a].id+" input[type=text], #"+m[a].id+" select")[0].focus())}function q(){for(var c=0,c=1;c<e.length;c++)a.inside&&0<T.length?(b("#"+m[c].id).remove(),b("div[data-replace="+m[c].id+"]").replaceWith(e[c])):b("#"+m[c].id).replaceWith(e[c]);0<T.length&&b("#"+m[0].id).replaceWith(e[0]);b('[data-test-table="'+a.id+'"]').remove();z.apply(x,m);b("#"+a.id).length&&b("#"+
a.id)[0].scrollIntoView();D(1);N.hide()}function r(c){var d="",e="",f=0;try{var n=b("#"+c.id),q="";c.form&&(q=' form="'+c.id+'_frm"');c.fieldset&&(n.wrapInner('<fieldset name="'+c.id+'"'+q+' class="'+X+'">\n</fieldset>\n'),c.legend&&b('fieldset[name="'+c.id+'"]',n).prepend("\n<legend>"+c.legend+"</legend>\n"));c.form&&n.wrapInner('\n<form id="'+c.id+'_frm" name="'+c.id+'" class="'+(c.formclass?c.formclass:jb)+'">\n</form>\n');e=' aria-controls="';for(f=0;f<k.length;f++)e+=k[f],f<k.length-1&&(e+=" ");
e+='"';("slide"===c.flow||"checker"===a.type)&&2<m.length&&(d+='<div id="'+c.id+'_sldctrl" class="'+kb+'">\n',d+='<button type="button" id="'+c.id+'_sldctrl_prev"'+(c["wai-aria"]?e:"")+' title="'+h.titleprev+'"'+(a["wai-aria"]?' aria-label="'+h.titleprev+'"':"")+' class="'+lb+(C?" "+I:"")+'">',d+=h.previous,d+="</button>\n",d+='<span id="'+c.id+'_sldctrl_info" class="'+mb+'">x/x</span>\n',d+='<button type="button" id="'+c.id+'_sldctrl_next"'+(c["wai-aria"]?e:"")+' title="'+h.titlenext+'"'+(a["wai-aria"]?
' aria-label="'+h.titlenext+'"':"")+' class="'+nb+(C?" "+I:"")+'">',d+=h.next,d+="</button>\n",d+="</div>\n");f="";"train"===c.flow&&2<m.length&&(d+='<div id="'+c.id+'_trnslider" class="'+sb+'">\n',d+='<div id="'+c.id+'_trnsliderprg"'+(a["wai-aria"]?' role="progressbar"':"")+' class="'+tb+'">\n',d+="</div>\n",d+='<div id="'+c.id+'_trnslidertxt" class="'+ub+'">\n',d+="</div>\n",d+="</div>\n",d+='<div id="'+c.id+'_trnctrl" class="'+ob+'">\n',d+='<button type="button" id="'+c.id+'_trnctrl_next"'+(c["wai-aria"]?
e:"")+' title="'+h.titlenext+'"'+(a["wai-aria"]?' aria-label="'+h.titlenext+'"':"")+' class="'+xa+(C?" "+I:"")+'">',d+=h.next,d+="</button>\n",d+="</div>\n",f=' style="display: none;"');var d=d+('<div id="'+c.id+'_btnbox" '+f+' class="'+qb+'">\n'),d=d+('<button type="button" id="'+c.id+'_btn" title="'+h.titlecheck+'"'+(a["wai-aria"]?' aria-label="'+h.titlecheck+'"':"")+' class="'+rb+(C?" "+I:"")+'">'),d=c.button?d+c.button:d+h.check,d=d+"</button>\n",d=d+"</div>\n",d=d+('<div id="'+c.id+'_out" class="'+
ia+'">\n</div>\n'),d=d+('<div id="'+c.id+'_results" style="display: none;">\n</div>\n'),r=b("#"+c.id+' fieldset[name="'+c.id+'"]'),t=b("#"+c.id+' form[name="'+c.id+'"]');r.length?r.append(d):t.length?t.append(d):n.append(d);var u=b('[data-info-bottom="'+c.id+'"]').html();if(u){var w='<div id="'+c.id+'_info_bottom" class="'+Ta+'">'+u+"</div>\n";r.length?r.append(w):t.length?t.append(w):n.append(w)}a["wai-aria"]&&0<b("#"+a.id+"_info_aria").length&&b("#"+a.id+"_btn").attr("aria-describedby",a.id+"_info_aria")}catch(v){G&&
alert("makeHtmlTest(): "+v)}return d}function J(c,d){try{var e=d||0,f=!0;-1==e&&(f=!1,e=1);if(0!==k.length){e&&(w=e-1);switch(c){case "prev":w--;break;case "next":w++}for(e=0;e<k.length;e++)e==w?(b("#"+k[e]).show(),a["wai-aria"]&&b("#"+k[e]).attr("aria-hidden",!1)):(b("#"+k[e]).hide(),a["wai-aria"]&&b("#"+k[e]).attr("aria-hidden",!0));0===w?(b("#"+a.id+"_sldctrl_prev").css("visibility","hidden"),f&&b("#"+a.id+"_sldctrl_next").focus(),a["wai-aria"]&&b("#"+a.id+"_sldctrl_prev").attr("aria-hidden",!0)):
(b("#"+a.id+"_sldctrl_prev").css("visibility","visible"),a["wai-aria"]&&b("#"+a.id+"_sldctrl_prev").attr("aria-hidden",!1));w===k.length-1?(b("#"+a.id+"_sldctrl_next").css("visibility","hidden"),b("#"+a.id+"_sldctrl_prev").focus(),a["wai-aria"]&&b("#"+a.id+"_sldctrl_next").attr("aria-hidden",!0)):(b("#"+a.id+"_sldctrl_next").css("visibility","visible"),a["wai-aria"]&&b("#"+a.id+"_sldctrl_next").attr("aria-hidden",!1));b("#"+a.id+"_sldctrl_info").html(parseInt(w+1,10)+"/"+parseInt(k.length,10));if(a["wai-aria"]){var h=
b("#"+a.id+"_sldctrl");h.attr("role","slider");h.attr("aria-valuenow",parseInt(w+1,10));h.attr("aria-valuemin",1);h.attr("aria-valuemax",parseInt(k.length,10));h.attr("aria-describedby",a.id+"_sldctrl_info")}f&&b("#"+k[w])[0].scrollIntoView()}}catch(m){G&&alert("runSlide(): "+m)}}function n(c,d){try{var e=d||0,f=!0;-1==e&&(f=!1,e=1);if(0!==k.length){e&&(w=e-1);switch(c){case "prev":w--;break;case "next":w++}for(e=0;e<k.length;e++)e==w?(b("#"+k[e]).show(),a["wai-aria"]&&b("#"+k[e]).attr("aria-hidden",
!1)):(b("#"+k[e]).hide(),a["wai-aria"]&&b("#"+k[e]).attr("aria-hidden",!0));b("#"+a.id+"_trnslider").length&&u(a.id+"_trnsliderprg",a.id+"_trnslidertxt",w+1,k.length,a.sliderinfo,a.slidercolor);w===k.length-1&&("test"===a.type&&(b("#"+a.id+"_trnctrl_next").text(a.button?a.button:h.check),b("#"+a.id+"_trnctrl_next").prop("title",h.titlecheck),b("#"+a.id+"_trnctrl_next").removeClass(xa).addClass(pb)),"checker"===a.type&&b("#"+a.id+"_trnctrl_next").hide());"checker"===a.type&&b("#"+a.id+"_trnctrl_next").prop("disabled",
!0);w+1<=m.length-1&&D(w+1);w===k.length&&("test"===a.type&&(b("#"+a.id+"_trnctrl").hide(),b("#"+a.id+"_trnslider").hide(),a["wai-aria"]&&(b("#"+a.id+"_trnctrl").attr("aria-hidden",!0),b("#"+a.id+"_trnslider").attr("aria-hidden",!0)),N.trigger("click")),w=0);f&&b("#"+k[w])[0].scrollIntoView()}}catch(n){G&&alert("runTrain(): "+n)}}function u(c,d,e,f,h,m){var k=0;c=b("#"+c);var n=b("#"+d);if(isNaN(e)||isNaN(f)||0===f||f<e)b(c).css("width","0%"),b("#txtnota").text("");else{k=e/f*100;c.css("width",Math.round(k).toString()+
"%");switch(h){case "none":n.html("");break;case "":case "def":n.html(e.toString()+"/"+f.toString());break;case "def%":n.html(Math.round(k).toString()+"%");break;default:n.html(h)}"rate"===m?20>k?c.css("background","red"):50>k?c.css("background","yellow"):70>k?c.css("background","#00CC00"):90>k?c.css("background","#009933"):c.css("background","#3366CC"):"def"===m||""===m?c.css("background","#33CC33"):"none"===m?c.css("background",""):"gradient"===m?c.css("background","linear-gradient(to right, rgba(0,153,0,0), rgba(0,153,0,1))"):
c.css("background",m);a["wai-aria"]&&(c.attr("aria-valuenow",e),c.attr("aria-valuemin",1),c.attr("aria-valuemax",f),c.attr("aria-describedby",d))}}function S(){var c="-",c=b(),d=0;z.objscore={};z.objscore.act=[];z.update=a.id;if(a.random)for(d=0;d<k.length;d++)var e=b("#"+a.id+'_results div[data-id="'+k[d]+'"]').clone(),c=c.add(e);else c=b("#"+a.id+"_results div");var f="",m=0,r=0;c.each(function(a){a=b(this).attr("data-weighting");m+=+a/100});b.isNumeric(m)||(m=+c.length);f+='<table data-test-table="'+
a.id+'" class="'+ya+'">\n';a.caption&&(f+="\t<caption>"+a.caption+"\n",a.details&&(f+="\t\t<details>\n",a.summary&&(f+="\t\t\t<summary>"+a.summary+"</summary>\n"),f+=a.details+"\n",f+="\t\t</details>\n"),f+="\t</caption>\n");f+="\t<thead>\n";f+='\t\t<tr class="'+za+'"><th>'+h.question+"</th><th>"+h.success+"</th><th>"+h.points+"</th></tr>\n";f+="\t</thead>\n";f+="\t<tbody>\n";c.each(function(c){var d=b(this).attr("data-type"),e=b(this).attr("data-id"),l=b(this).attr("data-weight"),g=b(this).attr("data-weighting"),
k=b(this).attr("data-lighting"),n={},q=0,t=Math.round(a.qbase*g/m)/100,p="0%";if("none"===l)l='<span title="'+h.notanswered+'">(0%)</span>',n.success="(0%)";else{0==l&&0<Math.abs(k)&&(l-=Math.abs(k));q=l/100*(+g/100)/m*10;r+=q;q=parseFloat(Math.round(100*q)/100);10!=a.qbase&&(q=a.qbase*q/10,q=parseFloat(Math.round(100*q)/100));if("single"===d){var u=b(this).attr("data-selected");if(u){var w="",w=50>l?sa:60>l?Qa:70>l?Ra:90>l?Sa:ta;b("[for="+u+"]").addClass(w+(C?" "+I:""))}}"multi"===d&&b("#"+e+" input:checked").each(function(){"true"===
b(this).attr("data-ok")?b(this).parent().addClass(ta+(C?" "+I:"")):b(this).parent().addClass(sa+(C?" "+I:""))});p=l+="%";n.success=l}(u=b("#"+e+" legend").text())||(u=h.question+" "+(c+1));w=' class="'+Aa+'"';c%2&&(w=' class="'+Ba+'"');var x="";100>+g&&(x=' <span title="'+h.weighting+'">(x'+ +g/100+")</span>");var y="";a.flow&&(y=' data-goto="'+parseInt(c+1,10)+'"');p=h.actscore.replace("$score$",q).replace("$ptot$",t).replace("$act$",c+1).replace("$%$",p).replace("$total$",a.qbase);f+="\t\t<tr"+
w+'><td><a href="#'+e+'"'+y+""+(a["wai-aria"]?' aria-label="'+p+'"':"")+' title="'+p+'"><span class="'+ma+'">#'+(c+1)+'</span> <span class="'+na+'">'+u+"</span></a>"+x+"</td>";f+="<td>"+l+"</td><td>"+q+"<sub>/"+a.qbase+"</sub></td></tr>\n";n.type=d;n.id=e;n.name=u;n.weighting=+g;n.lighting=+k;n.score=q;n.ptsplay=t;z.objscore.act.push(n)});f+="\t</tbody>\n";f+="\t<tfoot>\n";c=parseFloat(Math.round(100*r)/100);10!=a.qbase&&(c=a.qbase*c/10,c=parseFloat(Math.round(100*c)/100));0>c&&(c=0);z.score=c;f+=
'\t\t<tr class="'+Ca+'"><td class="'+vb+'" id="'+a.id+'_newtest"><button type="button" title="'+h.titlenewtest+'"'+(a["wai-aria"]?' aria-label="'+h.titlenewtest+'"':"")+' class="'+Oa+(C?" "+I:"")+'">'+h.newtest+'</button></td><td class="'+Ea+'">'+h.total+': </td><td id="'+a.id+'_fscore"'+(a["wai-aria"]?' aria-label="'+h.fscore.replace("$score$",c).replace("$total$",a.qbase)+'"':"")+' class="'+Fa+'" tabindex="0">'+c+"<sub>/"+a.qbase+"</sub></td></tr>\n";f+="\t</tfoot>\n";f+="</table>\n";z.objscore.total=
a.qbase;z.objscore.score=c;z.objscore.threshold=H;z.objscore.id=a.id;z.objscore.date=ga();b('[data-move-results="'+a.id+'"]').length?b('[data-move-results="'+a.id+'"]').append(f):b('[data-store-wrap="'+a.id+'"]').length?b('[data-store-wrap="'+a.id+'"]').before(f):b("#"+a.id+' fieldset[name="'+a.id+'"]').length?b("#"+a.id+' fieldset[name="'+a.id+'"]').append(f):b("#"+a.id+' form[name="'+a.id+'"]').length?b("#"+a.id+' form[name="'+a.id+'"]').append(f):b("#"+a.id).append(f);b("#"+a.id+"_fscore").focus();
b("#"+a.id+"_newtest").on("click",q);if(a.flow)b("[data-test-table="+a.id+"] [data-goto]").on("click",function(){"slide"===a.flow&&J("",b(this).attr("data-goto"));"train"===a.flow&&n("",b(this).attr("data-goto"))});N.hide();b('[data-test-table="'+a.id+'"]').length&&b('[data-test-table="'+a.id+'"]')[0].scrollIntoView();a.storage&&xb(a.storage,a.storagekey,a.id,{type:"jsgeork.test",id:a.id,name:a.name,score:c.toString(),qbase:a.qbase.toString(),date:ga()});try{"function"===typeof a.oncheck&&a.oncheck.call(z)}catch(t){G&&
alert("test.oncheck: "+t)}d=!1;c>=H&&(d=!0);if(d){c=b('[data-info-ok="'+a.id+'"]');c.length&&b("#"+a.id+"_out").append('\t<div class="'+P+'">\n'+c.html()+"</div>\n");try{"function"===typeof a.onok&&a.onok.call(z)}catch(u){G&&alert("test.onok: "+u)}}else{c=b('[data-info-ko="'+a.id+'"]');c.length&&b("#"+a.id+"_out").append('\t<div class="'+V+'">\n'+c.html()+"</div>\n");try{"function"===typeof a.onko&&a.onko.call(z)}catch(w){G&&alert("test.onko: "+w)}}try{z[a.id]=z.objscore}catch(x){}}var m=arguments,
a,e=[],k=[],w=0,t=0,H=50,T,N,C=!0;try{if("object"!==typeof c)throw new M({name:"Data error",message:"bad test config object"});if(!arguments[1]||"object"!==typeof arguments[1])throw new M({name:"Data error "+(c.name||c.legend),message:"bad test activity object"});if(!Ha(c.id,c.name||c.legend))if(U.jQuery){c.lang&&Q(userOpt.lang);zb=c;a=b.extend({},Ja,zb);T=b("#"+a.id);"pager"===a.type&&(a.flow="slide");"checker"===a.type&&(a.flow="train");a.qbase=parseInt(a.qbase,10);switch(a.qbase){case 100:case 20:case 10:case 9:case 8:case 7:case 6:case 5:break;
default:a.qbase=10}C="csshexent"===a.icons?!0:!1;z.lastcall=a.id;z.score="-";z.total=a.qbase;H=parseInt(a.threshold,10);b.isNumeric(H)&&0<H&&100>=H||(H=50);H=H/100*a.qbase;H=parseFloat(Math.round(100*H)/100);z.threshold=H;z.objscore=null;z.update=a.id;0<T.length&&(e[0]=b(b("<div></div>").html(b("#"+arguments[t].id).clone())).html());for(t=1;t<arguments.length;t++)e[t]=b(b("<div></div>").html(b("#"+arguments[t].id).clone())).html();if(("slide"===a.flow||"train"===a.flow)&&2<m.length)for(t=1;t<arguments.length;t++)k.push(arguments[t].id);
r(a);if(a.inside&&0<T.length){for(var A=[],t=1;t<arguments.length;t++)A[t-1]=b("#"+arguments[t].id).replaceWith('<div data-replace="'+arguments[t].id+'"></div>');for(var B=[],t=0;t<A.length;t++)B.push(t);a.random&&B.sort(function(){return 0.5-Math.random()});for(t=A.length-1;-1<t;t--)b("#"+a.id).prepend(A[B[t]])}if("checker"===a.type)for(t=1;t<arguments.length;t++)arguments[t].onchecker=t==arguments.length-1?function(){var c=b('[data-info-ok="'+a.id+'"]');c.length&&(b("#"+a.id+"_out").append('<div class="'+
P+'">'+c.html()+"</div>"),b('[data-info-ok="'+a.id+'"]').show(),b("#"+a.id+"_trnslider").hide(),b("#"+a.id+"_sldctrl").css("display","table"),J(arguments.length-1))}:function(){b("#"+a.id+"_trnctrl_next").prop("disabled",!1)};for(t=1;t<arguments.length;t++)"pager"===a.type||"checker"===a.type?x(arguments[t]):x(arguments[t],a);if(("slide"===a.flow||"train"===a.flow)&&2<m.length)for(a.random&&k.sort(function(){return 0.5-Math.random()}),t=1;t<k.length;t++)b("#"+k[t]).hide(),a["wai-aria"]&&b("#"+k[t]).attr("aria-hidden",
!0);b('[data-move-btncheck="'+a.id+'"]').length&&b('[data-move-btncheck="'+a.id+'"]').html(b("#"+a.id+"_btnbox"));b('[data-move-btnctrl="'+a.id+'"]').length&&("slide"===a.flow&&b('[data-move-btnctrl="'+a.id+'"]').html(b("#"+a.id+"_sldctrl")),"train"===a.flow&&b('[data-move-btnctrl="'+a.id+'"]').html(b("#"+a.id+"_trnctrl")));b('[data-move-prgbar="'+a.id+'"]').length&&b('[data-move-prgbar="'+a.id+'"]').html(b("#"+a.id+"_trnslider"));N=b("#"+a.id+"_btn");if("pager"===a.type||"checker"===a.type)N.hide();
else N.on("click",S);("slide"===a.flow||"checker"===a.type)&&2<m.length&&(J("",-1),b("#"+a.id+"_sldctrl_prev").on("click",function(){J("prev")}),b("#"+a.id+"_sldctrl_next").on("click",function(){J("next")}),"checker"===a.type&&b("#"+a.id+"_sldctrl").hide());"train"===a.flow&&2<m.length&&(b("#"+a.id+"_sldctrl_next").text(h.next),b("#"+a.id+"_trnslider").length&&(u(a.id+"_trnsliderprg",a.id+"_trnslidertxt",w+1,k.length,a.sliderinfo,a.slidercolor),b("#"+a.id+"_trnslider").show(),a["wai-aria"]&&b("#"+
a.id+"_trnslider").attr("aria-hidden",!1)),"checker"===a.type&&b("#"+a.id+"_trnctrl_next").prop("disabled",!0),b("#"+a.id+"_trnctrl_next").on("click",function(){n("next")}));if("test"===a.type&&a.showstorage){var y=qa(a.storage,a.storagekey,a.id,a.delstorage);if(y='<div data-store-wrap="'+a.id+'">\n'+y+"</div>\n")b("#"+a.id+' fieldset[name="'+a.id+'"]').length?b("#"+a.id+' fieldset[name="'+a.id+'"]').append(y):b("#"+a.id).append(y),Ia(a.storage,a.storagekey,a.id,'[data-store-wrap="'+a.id+'"] '),b('[data-storage-tblbox="'+
a.id+'"] .'+wa).hide().attr("aria-hidden",!0),b('[data-storage-tblbox="'+a.id+'"] .'+va).show().attr("aria-hidden",!1)}try{"function"===typeof a.onready&&a.onready.call(z)}catch(F){G&&alert("test.onready: "+F)}}else R.getElementById(c.id).innerHTML="<span style='color: red;'>This requires jQuery!</span>"}catch(O){O instanceof M?O.show():G&&alert("setTest(): "+O)}}var zb={},Ja={id:"",type:"test",name:"",formclass:"",form:!0,fieldset:!0,legend:"",caption:"",details:"",summary:"","wai-aria":!0,icons:"csshexent",
inside:!1,random:!1,flow:"",slidercolor:"",sliderinfo:"",qbase:10,threshold:50,storage:"local",storagekey:"",showstorage:!0,delstorage:!0,onready:"",oncheck:"",onok:"",onko:""},W={},Ab={id:"",name:"",type:"single",fieldset:!0,legend:"","wai-aria":!0,clase:"",list:"",hint:!0,opt:[],boxs:{},gaps:{},attempts:3,random:!1,weighting:100,lighting:0,optsuccess:!0,threshold:100,icons:"csshexent",storage:"",storagekey:"",fillfromstorage:!1,showstorage:!0,delstorage:!0,url:"",onready:"",oncheck:"",oncomplete:"",
onok:"",onko:""},Bb={text:"Option X",answer:"optx",select:!1,weight:0},Cb={type:"text",values:[],decimals:"",tofixed:"",accuracy:"",weight:100,placeholder:"",casesensitive:!1,autocomplete:"",adjustgaps:"","aria-label":h.inpfill},Db={words:[],showwords:!1,weight:100,placeholder:"",casesensitive:!1,autocomplete:"",adjustgaps:"","aria-label":h.fillthegapinp};return{Question:x,Test:z,Eval:function(c){function z(){n?(U.clearInterval(n),n=null,b("#"+c.id+"_timer").css("color","red"),b("#"+c.id+"_refresh button").css("border",
"2px solid red")):c.timer?(n=U.setInterval(function(){q.apply(this,r)},c.timer),b("#"+c.id+"_timer").css("color","inherit"),b("#"+c.id+"_refresh button").css("border","inherit")):q.apply(this,r)}function q(){function m(a,b,d){var e=null;"local"===c.storage&&localStorage&&(e=localStorage);"session"===c.storage&&sessionStorage&&(e=sessionStorage);e&&(C[d]?(d=JSON.parse(e.getItem(C[d]))||null)&&d[b]&&(a=d[b][d[b].length-1]):(d=JSON.parse(e.getItem(b))||null)&&(a=d[d.length-1]));return a}var a=0,e=x,
k=[],n=[],t=[],u=[],D=[],M=[],C=[],A=!0,B=arguments.length-1,a=0,y="-",F=0,O=0,g=50,d="";if("object"==typeof c&&c.id){c.qbase=c.qbase||10;"undefined"==typeof c["wai-aria"]&&(c["wai-aria"]=!0);c.threshold=c.threshold||100;"undefined"==typeof c.refresh&&(c.refresh=!0);c.names=c.names||"name";c.timer=c.timer||0;"local"===c.storage?localStorage||(c.storage=""):"session"!==c.storage||sessionStorage||(c.storage="");for(a=1;a<arguments.length;a++)"object"===typeof arguments[a]?(C.push(arguments[a].storagekey),
arguments[a].id&&(y="",A=arguments[a].url||"","name"===c.names&&(y=arguments[a].name||arguments[a].legend||arguments[a].id),"legend"===c.names&&(y=arguments[a].legend||arguments[a].name||arguments[a].id),e[arguments[a].id]||c.storage&&m(null,arguments[a].id,C.length-1)?(k.push(arguments[a].id),t.push(y),n.push(A)):(u.push(arguments[a].id),D.push(y),M.push(A)))):"string"===typeof arguments[a]&&(C.push(c.storagekey),A=c.url||"",e[arguments[a]]||c.storage&&m(null,arguments[a],C.length-1)?(k.push(arguments[a]),
n.push(A)):(u.push(arguments[a]),D.push(arguments[a]),M.push(A)));a=k.length;c.qbase=parseInt(c.qbase,10);switch(c.qbase){case 100:case 20:case 10:case 9:case 8:case 7:case 6:case 5:break;default:c.qbase=10}A="csshexent"===c.icons?!0:!1;b.each(k,function(a){var b=e[this];c.storage&&(b=m(null,this,a));b&&(a=b.weighting)&&(F+=+a/100)});b.isNumeric(F)||(F=+k.length);d+='<table data-activities-table="'+c.id+'" class="'+ya+'">\n';c.caption&&(d+="\t<caption>"+c.caption+"\n",c.details&&(d+="\t\t<details>\n",
c.summary&&(d+="\t\t\t<summary>"+c.summary+"</summary>\n"),d+=c.details+"\n",d+="\t\t</details>\n"),d+="\t</caption>\n");d+="\t<thead>\n";d+='\t\t<tr class="'+za+'"><th>'+h.question+"</th><th>"+h.success+"</th><th>"+h.points+"</th></tr>\n";d+="\t</thead>\n";d+="\t<tbody>\n";b.each(k,function(a){var b=e[this];c.storage&&(b=m(null,this,a));if(b){var f=b.date||"",g=this||c.id,l=n[a]||"",k=b.score,q=b.weighting,r=b.lighting,b=0,x=Math.round(c.qbase*q/F)/100,y="0%";0==k&&0<Math.abs(r)&&(k-=Math.abs(r));
b=k/100*(+q/100)/F*10;O+=b;b=parseFloat(Math.round(100*b)/100);10!=c.qbase&&(b=c.qbase*b/10,b=parseFloat(Math.round(100*b)/100));y=k+="%";f=f&&c.storage?"<br/><small>"+fa(f)+"</small>":"";(r=t[a])||(r=h.question+" "+(a+1));var p=' class="'+Aa+'"';a%2&&(p=' class="'+Ba+'"');var z="";100>+q&&(z=' <span title="'+h.weighting+'">(x'+ +q/100+")</span>");q=h.actscore.replace("$score$",b).replace("$ptot$",x).replace("$act$",a+1).replace("$%$",y).replace("$total$",c.qbase);d+="\t\t<tr"+p+'><td><a href="'+
l+"#"+g+'"'+(c["wai-aria"]?' aria-label="'+q+'"':"")+' title="'+q+'"><span class="'+ma+'">#'+(a+1)+'</span> <span class="'+na+'">'+r+"</span></a>"+z+f+"</td>";d+="<td>"+k+"</td><td>"+b+"<sub>/"+c.qbase+"</sub></td></tr>\n"}else u.push(this),D.push(this)});b.each(u,function(a){var b=this||c.id,e=M[a]||"",f="",f=D[a],g=h.actnosubmit;d+='\t\t<tr class="'+Ga+'"><td colspan="3"><a href="'+e+"#"+b+'"'+(c["wai-aria"]?' aria-label="'+g+'"':"")+' title="'+g+'"><span class="'+ma+'">#'+(a+1)+'</span> <span class="'+
na+'">'+f+"</span></a></td>";d+="</tr>\n"});d+="\t</tbody>\n";a<B&&(d+="\t<tbody>\n",d+='\t\t<tr class="'+Ga+'"><td colspan="3">'+a+"/"+B+h.actdone+"</td></tr>\n",d+="\t</tbody>\n");d+="\t<tfoot>\n";y=parseFloat(Math.round(100*O)/100);10!=c.qbase&&(y=c.qbase*y/10,y=parseFloat(Math.round(100*y)/100));0>y&&(y=0);var K="<td></td>",k=new Date,K=k.getHours(),f=k.getMinutes(),L=k.getSeconds(),f=10>f?"0"+f:f,L=10>L?"0"+L:L,P=h.refresh,Q=g="";c.timer&&(P=K+":"+f+"<small> "+L+"</small>",g=' style="cursor: pointer;"',
Q=" ("+Math.round(c.timer/1E3)+"s)");K=c.refresh?'<td class="'+Da+'" id="'+c.id+'_refresh"><button type="button" title="'+h.titlerefresh+'"'+(c["wai-aria"]?' aria-label="'+h.titlerefresh+'"':"")+' class="'+Pa+(A?" "+I:"")+'">'+P+"</button></td>":'<td class="'+Da+'" id="'+c.id+'_timer" title="'+h.lasttime+'">'+K+":"+f+"<small> "+L+"</small></td>";d+='\t\t<tr class="'+Ca+'">'+K+'<td class="'+Ea+'">'+h.total+': </td><td id="'+c.id+'_fscore"'+(c["wai-aria"]?' aria-label="'+h.fscore.replace("$score$",
y).replace("$total$",c.qbase)+'"':"")+' class="'+Fa+'" tabindex="0" title="'+h.lasttime+" "+k.getHours()+"h:"+k.getMinutes()+"m:"+k.getSeconds()+"s"+Q+'"'+g+">"+y+"<sub>/"+c.qbase+"</sub></td></tr>\n";d+="\t</tfoot>\n";d+="</table>\n";b('[data-activities-eval="'+c.id+'"]').length?b('[data-activities-eval="'+c.id+'"]').html(d):b("#"+c.id).html(d);c.refresh&&(b("#"+J+"_refresh").off("click",function(){q.apply(this,r)}),b("#"+J+"_refresh").on("click",function(){q.apply(this,r)}));c.timer&&(b("#"+c.id+
"_fscore").off("click",z),b("#"+c.id+"_fscore").on("click",z));A=!1;g=parseInt(c.threshold,10);b.isNumeric(g)&&0<g&&100>=g||(g=100);g=g/100*c.qbase;g=parseFloat(Math.round(100*g)/100);e[c.id]={};e[c.id].eval=y;e[c.id].threshold=g;e[c.id].date=ga();e[c.id].refresh=z;y>=g&&a>=B&&(A=!0);B=b('[data-info-ok="'+c.id+'"]');a=b('[data-info-ko="'+c.id+'"]');if(A){B.length&&B.show();a.length&&a.hide();try{"function"===typeof c.onok&&c.onok.call(e)}catch(S){G&&alert("activities.onok: "+S)}}else{B.length&&B.hide();
a.length&&a.show();try{"function"===typeof c.onko&&c.onko.call(e)}catch(R){G&&alert("activities.onko: "+R)}}}}var r=arguments,J=c.id,n=null,u=c.name||"Eval table";try{if("object"!==typeof c)throw new M({name:"Data error "+u,message:"bad eval config object"});if(!arguments[1]||"object"!==typeof arguments[1]&&"string"!==typeof arguments[1])throw new M({name:"Data error "+u,message:"bad eval activity object"});if(!Ha(J,u)){c.timer=c.timer||0;switch(c.timer){case "1s":c.timer=1E3;break;case "5s":c.timer=
5E3;break;case "10s":c.timer=1E4;break;case "30s":c.timer=3E4;break;case "1m":c.timer=6E4;break;case "5m":c.timer=3E5;break;case "10m":c.timer=6E5}!b.isNumeric(c.timer)||0>c.timer?c.timer=0:c.timer=parseInt(c.timer,10);n&&U.clearInterval(n);1E3<=c.timer&&(n=U.setInterval(function(){q.apply(this,r)},c.timer));q.apply(this,r)}}catch(D){D instanceof M?D.show():G&&alert("Eval(): "+D)}},getStorage:function(c,h,q,r,x){try{var n="",u="";x=x||!0;u="object"===typeof r?r.id:r;return(n=qa(h,q,r,x))&&b("#"+c).length?
(b("#"+c).append(n),Ia(h,q,u,"#"+c+" "),!0):!1}catch(z){G&&alert("getStorage(): "+z)}},ShowOptions:function(){alert(JSON.stringify(settings));return this}}}();Q.prototype.Questions=Ja;Q.prototype.modInfo=function(){var b=h.infbienvenida+oa+". \n\n";return{aboutMe:h.infme,getInfo:function(){var D=b,D=D+(h.infversion+"0.0.6. \n"),D=D+(h.infobjgbl+oa+". \n");return D+=h.infjq+" \n"}}}();fa.fn=Q.prototype;U.jsGeork=fa})(jQuery,document,window);